# -*- coding: utf-8 -*-
"""flask assigntment 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gBI06AKLntfVdeadnKWRUfEphfuQrxvB
"""



"""Q1. Explain GET and POST methods.


ANS:-
The GET and POST methods are two HTTP request methods used in web development to transmit data between a client (usually a web browser) and a server. The primary distinction between them lies in how they handle data transmission.

GET method is used for retrieving data from the server. When a client sends a GET request, it appends the data to the URL in the form of query parameters. This method is suitable for non-sensitive information, as the data is visible in the URL, making it less secure. GET requests are idempotent, meaning multiple identical requests have the same effect as a single request.

POST method, on the other hand, is used for submitting data to be processed to a specified resource. Unlike GET, the data is not appended to the URL; instead, it is sent in the request body. This makes POST more secure for transmitting sensitive information, as the data is not exposed in the URL. POST requests are not idempotent, and multiple identical requests may have different effects.
"""



"""Q2. Why is request used in Flask?



##ANS:-
In Flask, the request object is used to access incoming data from a client's HTTP request. It allows a Flask application to retrieve form data, query parameters, and other information sent by a client as part of an HTTP request.

The request object in Flask provides methods and attributes to access various parts of the incoming request, such as form data, URL parameters, headers, and the request method. By using the request object, a Flask application can dynamically respond to different types of incoming data and take appropriate actions based on the content of the request.

## Q3. Why is redirect() used in Flask?

## ANS:-
In Flask, the redirect() function is used to perform a redirect to a different endpoint or URL. This function is particularly useful when you want to guide the user to another page or route after processing a form submission or completing a certain action. It helps in keeping the application organized and enhances the user experience by directing them to the appropriate page.
"""



"""## Q4. What are templates in Flask? Why is the render_template() function used?"""



"""## ANS:-
In Flask, templates are used to separate the presentation layer (HTML) from the application logic (Python code). Templates allow us to dynamically generate HTML content by embedding placeholders for data that will be filled in when rendering the template. This separation of concerns makes it easier to manage and maintain code, especially in web applications with complex user interfaces.

The render_template() function in Flask is used to render these templates and return the resulting HTML to the client's browser. This function takes the name of the template file as an argument and, optionally, additional parameters to pass data to the template
"""

